### ISSUE TITLE
Consider moving this tool into tc39/test262

### ISSUE THREAD

**Issue by ptomato** [bocoup/test262-regexp-generator#3]
We are considering copying this tool into the tc39/test262 repository so that it lives close by the tests that it generates. Any suggestions/concerns?

**Comment by jugglinmike** [comment]
None that come to mind!

**Comment by ptomato** [comment]
Done in https://github.com/tc39/test262/pull/4303. Some changes were necessary to match subsequent changes to the tests that weren't reflected in the script, so extra reviews are appreciated.
